insert into spacecraft (spacecraft_name, movie, pilot) values ('Millennium Falcon', 'Star Wars', 'Han Solo');
insert into spacecraft (spacecraft_name, movie, pilot) values ('x-wing', 'Star Wars', 'Luke Skywalker');
insert into spacecraft (spacecraft_name, movie, pilot) values ('Star Destroyer', 'Star Wars', 'Imperial troopers');
insert into spacecraft (spacecraft_name, movie, pilot) values ('TIE Fighter', 'Star Wars', 'Imperial troopers');
insert into spacecraft (spacecraft_name, movie, pilot) values ('USS Enterprise', 'Star Trek', 'James T. Kirk');
insert into spacecraft (spacecraft_name, movie, pilot) values ('Nostromo', 'Alien', 'Dallas');
insert into spacecraft (spacecraft_name, movie) values ('Sulaco', 'Alien');
insert into spacecraft (spacecraft_name, movie, pilot) values ('Spinner', 'Blade Runner', 'Rick Decarad');
insert into spacecraft (spacecraft_name, movie, pilot) values ('Endurance', 'Interstellar', 'Cooper');
insert into spacecraft (spacecraft_name, movie, pilot) values ('Machine', 'Contact', 'Ellie Arroway');